### ISSUE TITLE
Start using poetry for package management?

### ISSUE THREAD

**Issue by sarahbridle** [FixOurFood/AgriFoodPy#7]
I'm just pip installing rasterio, but wondering if there is an easy way to log this change / make it simple for future users - perhaps poetry?

[note to self - we're using conda here not pip, don't mix. do conda install rasterio instead]

or how do I edit the FOF setup?

**Comment by sarahbridle** [comment]
- [ ] tthing here 
- [ ] another

**Comment by kaedonkers** [comment]
Having said that, you can include pip packages in a conda environment if you found that there were packages or package versions that were only sourced from pip and not conda. 

For example the `environment.yaml` could look like:
```yaml
name: conda-env
dependencies:
  - python
  - pandas
  - pip
  - pip:
    - rasterio
```
